# ▗▖  ▗▖▗▄▄▄▖▗▄▄▄▖▗▄▄▖  ▗▄▖      ▗▄▖  ▗▄▄▖
# ▐▛▚▖▐▌  █    █  ▐▌ ▐▌▐▌ ▐▌    ▐▌ ▐▌▐▌   
# ▐▌ ▝▜▌  █    █  ▐▛▀▚▖▐▌ ▐▌    ▐▌ ▐▌ ▝▀▚▖
# ▐▌  ▐▌▗▄█▄▖  █  ▐▌ ▐▌▝▚▄▞▘    ▝▚▄▞▘▗▄▄▞▘
# Github : @Nitro-OS

# See https://wiki.hypr.land/Configurin/Monitors/
# monitor=NAME,RESOLUTION,POSITION,SCALE

# LEFT (start point)
monitor=HDMI-A-1,1920x1080@60,0x0,1

# RIGHT (shift right by width)
monitor=eDP-1,1920x1080@144,1920x0,1

# SINGLE MONITOR
# monitor=eDP-1,1920x1080@144,0x0,1

# HOW TO CHANGE POSITION:
# 0x0 = left/top start
# add screen width (1920) to move right
# for swap → just switch 0x0 and 1920x0

# apply:
# hyprctl reload
