#!/usr/bin/env bash
# shellcheck disable=SC2034

iso_name="nitroos"
iso_label="NITROOS_$(date --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%Y%m)"
iso_publisher="NitroOS (based on Arch Linux) <https://github.com/nitro-os>"
iso_application="NitroOS Live System (Arch-based)"
iso_version="$(date --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%Y.%m.%d)"
install_dir="arch"
buildmodes=('iso')
bootmodes=('bios.syslinux'
           'uefi.systemd-boot')
pacman_conf="pacman.conf"
airootfs_image_type="squashfs"
airootfs_image_tool_options=('-comp' 'xz' '-Xbcj' 'x86' '-b' '1M' '-Xdict-size' '1M')
bootstrap_tarball_compression=('zstd' '-c' '-T0' '--auto-threads=logical' '--long' '-19')
file_permissions=(
  ["/etc/shadow"]="0:0:400"
  ["/etc/gshadow"]="0:0:400"
  ["/root"]="0:0:750"
  ["/root/.automated_script.sh"]="0:0:755"
  ["/root/.gnupg"]="0:0:700"
  ["/home/nitroos"]="1000:1000:755"
  ["/home/nitroos/.automated_script.sh"]="1000:1000:755"
  ["/home/nitroos/.zlogin"]="1000:1000:644"
  ["/home/nitroos/.zshrc"]="1000:1000:644"
  ["/etc/sudoers.d"]="0:0:755"
  ["/etc/sudoers.d/10-nitroos"]="0:0:440"
  ["/etc/skel/Desktop/calamares.desktop"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/battery.sh"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/wallpaper.sh"]="0:0:755"
  ["/etc/skel/.config/rofi/clipboard/clipboard.sh"]="0:0:755"
  ["/etc/skel/.config/rofi/help/help.sh"]="0:0:755"
  ["/etc/skel/.config/rofi/help/parse_bindings.py"]="0:0:755"
  ["/etc/skel/.config/rofi/launchers/launcher.sh"]="0:0:755"
  ["/etc/skel/.config/rofi/powermenu/powermenu.sh"]="0:0:755"
  ["/etc/skel/.config/rofi/user/apps.sh"]="0:0:755"
  ["/etc/skel/.config/rofi/wallpaper/wallpaper.sh"]="0:0:755"
  ["/etc/skel/.config/waybar/scripts/backlight"]="0:0:755"
  ["/etc/skel/.config/waybar/scripts/bluetooth"]="0:0:755"
  ["/etc/skel/.config/waybar/scripts/hyprsunset-status.sh"]="0:0:755"
  ["/etc/skel/.config/waybar/scripts/hyprsunset-toggle.sh"]="0:0:755"
  ["/etc/skel/.config/waybar/scripts/network"]="0:0:755"
  ["/etc/skel/.config/waybar/scripts/power.sh"]="0:0:755"
  ["/etc/skel/.config/waybar/scripts/update"]="0:0:755"
  ["/etc/skel/.config/waybar/scripts/volume"]="0:0:755"
  ["/etc/polkit-1/rules.d"]="0:polkitd:750"
  ["/etc/polkit-1/rules.d/49-calamares.rules"]="0:polkitd:640"
  ["/etc/polkit-1/rules.d/50-org.freedesktop.NetworkManager.rules"]="0:polkitd:640"
  ["/etc/nitroos/calamares.desktop"]="0:0:644"
  ["/etc/nitroos/os-release"]="0:0:644"
  ["/usr/local/bin/nhttp"]="0:0:755"
  ["/usr/local/bin/npk"]="0:0:755"
  ["/usr/local/bin/choose-mirror"]="0:0:755"
  ["/usr/local/bin/Installation_guide"]="0:0:755"
  ["/usr/local/bin/livecd-sound"]="0:0:755"
  ["/usr/local/bin/nitroos-init-user"]="0:0:755"
  ["/usr/local/bin/nitroos-prepare-installer"]="0:0:755"
  ["/usr/local/bin/calamares-launcher"]="0:0:755"
  ["/etc/mkinitcpio.conf"]="0:0:644"
  ["/etc/pam.d/hyprlock"]="0:0:644"
  ["/etc/calamares/modules/bootloader/main.py"]="0:0:755"
  ["/etc/calamares/modules/bootloader/module.desc"]="0:0:644"
)

