title    Nitro OS install medium (Safe Graphics / nomodeset, %ARCH%, UEFI)
sort-key 01-nomodeset
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% nomodeset copytoram=n
