modules-search: [ /etc/calamares/modules, /usr/lib/calamares/modules ]

instances:
  - id:       clean_live_user
    module:   shellprocess
    config:   shellprocess-clean_live_user.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - shellprocess@clean_live_user
      - initcpiocfg
      - initcpio
      - grubcfg
      - bootloader
      - umount
  - show:
      - finished

branding: nitroos

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
