---
overwrite: false
keep_distributor: false

defaults:
    GRUB_TIMEOUT: 5
    GRUB_DEFAULT: 0
    GRUB_DISTRIBUTOR: "NitroOS"
    GRUB_CMDLINE_LINUX_DEFAULT: "quiet loglevel=3"
    GRUB_CMDLINE_LINUX: ""
    GRUB_DISABLE_OS_PROBER: "false"
