---
efi:
    mountPoint:         "/boot/efi"
    recommendedSize:    512MiB
    minimumSize:        100MiB
    label:              "EFI"

efiFileSystem: "fat32"
defaultFileSystemType: "ext4"
availableFileSystemTypes:
  - ext4
  - btrfs
  - xfs
  - f2fs

enableLuksAutomatedPartitioning: true

userSwapChoices:
    - none
    - small
    - suspend
    - file

drawPartitionLabels: true

initialPartitioningChoice: none
initialSwapChoice: none

defaultPartitionTableType: gpt

alwaysShowPartitionLabels: true

allowManualPartitioning: true
