---
dontChroot: false
timeout: 120
script:
    - "-rm -rf /home/nitroos"
    - "-rm -f /etc/sudoers.d/10-nitroos"
    - "-rm -f /etc/systemd/system/getty@tty1.service.d/autologin.conf"
    - "-rm -f /etc/systemd/system/etc-pacman.d-gnupg.mount"
    - "-rm -f /etc/systemd/system/multi-user.target.wants/nitroos-init-user.service"
    - "-rm -f /etc/systemd/system/multi-user.target.wants/choose-mirror.service"
    - "-rm -f /etc/systemd/system/multi-user.target.wants/pacman-init.service"
    - "-rm -f /etc/systemd/system/multi-user.target.wants/livecd-talk.service"
    - "-rm -f /etc/systemd/system/sound.target.wants/livecd-alsa-unmuter.service"
    - "-rm -f /etc/systemd/system/nitroos-init-user.service"
    - "-rm -f /etc/systemd/system/choose-mirror.service"
    - "-rm -f /etc/systemd/system/pacman-init.service"
    - "-rm -f /etc/systemd/system/livecd-talk.service"
    - "-rm -f /etc/systemd/system/livecd-alsa-unmuter.service"
    - "-rm -f /etc/polkit-1/rules.d/49-calamares.rules"
    - "-rm -f /etc/skel/Desktop/calamares.desktop"
    - "-rm -f /usr/share/applications/calamares.desktop"
    - "-rm -f /etc/sddm.conf.d/kde_settings.conf"
    - "-rm -f /root/.automated_script.sh"
    - "-rm -f /root/install.txt"
    - "-rm -f /etc/mkinitcpio.conf.d/archiso.conf"
    - "/bin/sh -c 'printf \"# mkinitcpio preset file for the linux package\\nALL_config=\\\"/etc/mkinitcpio.conf\\\"\\nALL_kver=\\\"/boot/vmlinuz-linux\\\"\\nPRESETS=(\x27default\x27 \x27fallback\x27)\\ndefault_image=\\\"/boot/initramfs-linux.img\\\"\\nfallback_image=\\\"/boot/initramfs-linux-fallback.img\\\"\\nfallback_options=\\\"-S autodetect\\\"\\n\" > /etc/mkinitcpio.d/linux.preset'"

