---
defaultGroups:
    - wheel
    - audio
    - video
    - input
    - storage
    - network
    - power
    - optical
    - lp
    - kvm

autologinGroup:  autologin
sudoersGroup:    wheel
setRootPassword: true
doAutologin:     false

avatarFilePath:  ~/.face

defaultShell:    /bin/zsh
